#!/bin/ksh

# ls
alias ls='ls -F --color=auto'
alias lsa='ls -lah --color=auto'
alias l='ls -la --color=auto'
alias ll='ls -l --color=auto'
alias la='ls -lA --group-directories-first --color=auto'
alias ls.='ls -d .* --color=auto'
alias sl=ls

# directory management
alias ..='cd ..'
alias cd..='cd ..'

# confirmation on mass file changes
alias mv='mv -i'
alias cp='cp -i'
alias ln='ln -i'

# prompt if changing perms or owner on more than 3 files at a time
alias chown='chown --preserve-root'
alias chmod='chmod --preserve-root'
alias chgrp='chgrp --preserve-root'

# mount
alias mount='mount |column -t'

# htop
if (`which htop >/dev/null 2>&1`); then
  alias top='htop'
fi

# diff
if (`which colordiff >/dev/null 2>&1`); then
  alias diff='colordiff'
fi

# wget
alias wget='wget -c' # enable continue of downloads

# tar
alias untar='tar -zxvf'

# rsync
if (`which rsync >/dev/null 2>&1`); then
  alias rsync-copy='rsync -avzh --progress --stats'
  alias rsync-mirror='rsync -avzh --progress --stats --delete-before --delete-excluded'
  alias rsync-move='rsync -avzh --progress --stats --remove-source-files'
  alias rsync-synchronize='rsync -avzuh --progress --stats --delete'
  alias rsync-update='rsync -avzuh --progress --stats'
fi

# grep
alias grep-nocomments='grep -Ev '\''^( *)(#|$|;)'\''' # greps a file for lines without comments
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# dmesg
alias dmesg='dmesg -L auto -T'

# disk, partition, folder and file usage commands
  # disk usage in the current directory
  alias usagedirectory='du -ch 2> /dev/null | tail -1'

  # total disk usage
  alias usagedisk='df -hl --total | tail -1'

  # individual partition usages without the temporary memory values
  alias usagepartition='df -hlT --exclude-type=tmpfs --exclude-type=devtmpfs'

  # largest folders within current dir
  function usagehogs {
    du -k * 2>/dev/null | sort -nr | awk '{ if($1>=1024*1024) {size=$1/1024/1024; unit="G"} else if($1>=1024) {size=$1/1024; unit="M"} else {size=$1; unit="K"}; if(size<10) format="%.1f%s"; else format="%.0f%s"; res=sprintf(format,size,unit); printf "%-8s %s\n",res,$2 }'
  }
