#!/usr/bin/env ksh

# set default variables
  TTY_COLOR=''
  GNU_TTY_COLOR=''
  GNU_PRESERVE=''
  GNU_i=''
  GNU=''

# detect if tty color support is installed
  if (`command -v dircolor >/dev/null 2>&1`); then
    TTY_COLOR=' --color=tty'
    GNU_TTY_COLOR=' --color=tty'
  fi

# detect if gnu coreutils are installed
  if (`command -v gdircolors >/dev/null 2>&1`); then
    GNU_TTY_COLOR=' --color=tty'
    GNU_PRESERVE=' --preserve-root'
    GNU_i=' -i'
    GNU='g'
  fi

# ls
  alias ls=$GNU'ls -F'$GNU_TTY_COLOR
  alias lsa=$GNU'ls -lah'$GNU_TTY_COLOR
  alias l=$GNU'ls -la'$GNU_TTY_COLOR
  alias ll=$GNU'ls -l'$GNU_TTY_COLOR
  alias la=$GNU'ls -lA --group-directories-first'$GNU_TTY_COLOR
  alias ls.=$GNU'ls -d .*'$GNU_TTY_COLOR

# directory management
  alias ..='cd ..'
  alias cd..='cd ..'

# confirmation on mass file changes
  alias mv=$GNU'mv'$GNU_i
  alias cp=$GNU'cp'$GNU_i
  alias ln=$GNU'ln'$GNU_i

# prompt if changing perms or owner on more than 3 files at a time
  alias chown=$GNU'chown'$GNU_PRESERVE
  alias chmod=$GNU'chmod'$GNU_PRESERVE
  alias chgrp=$GNU'chgrp'$GNU_PRESERVE

# ssh
  # alias ssh to change the term to xterm before the session starts
  alias ssh='TERM=xterm ssh'

# mount
  alias mount='mount |column -t'

# who
  # show user idle time
  alias who='who -u'

# htop
  if (`command -v htop >/dev/null 2>&1`); then
    alias top='htop'
  fi

# diff
  if (`command -v colordiff >/dev/null 2>&1`); then
    alias diff='colordiff'
  fi

# wget
  # enable continue of downloads
  alias wget='wget -c'

# tar
  alias untar='tar -zxvf'

# most
  if (`command -v most >/dev/null 2>&1`); then
    export PAGER='most'
  fi

# rsync
  if (`command -v rsync >/dev/null 2>&1`); then
    alias rsync-copy='rsync -avzh --progress --stats'
    alias rsync-mirror='rsync -avzh --progress --stats --delete-before --delete-excluded'
    alias rsync-move='rsync -avzh --progress --stats --remove-source-files'
    alias rsync-synchronize='rsync -avzuh --progress --stats --delete'
    alias rsync-update='rsync -avzuh --progress --stats'
  fi

# cli to online paste aliases
  alias termbin='nc termbin.com 9999'
  alias clibin='curl -q -F "clbin=<-" https://clbin.com; echo Append "?hl" to the url for highlighting'
  alias pastebin=clibin

# grep
  alias grep=$GNU'grep'$GNU_TTY_COLOR
  alias fgrep=$GNU'fgrep'$GNU_TTY_COLOR
  alias egrep=$GNU'egrep'$GNU_TTY_COLOR

# grep output for lines without common comment
  alias nocomments='grep -Evi '\''^( *)(#|$|;|//|--|rem|::|\"|\|\|)'\'''
  alias comments='grep -Ei '\''^(#|;|//|--|rem|::|\"|\|\|)'\'''

# dmesg
  if [[ `uname` == 'Linux' ]]; then
    alias dmesg='dmesg -L auto -T'
  fi

# disk, partition, folder and file usage commands
  # disk usage in the current directory
  alias usagedirectory='du -ch 2> /dev/null | tail -1'

  # total disk usage
  alias usagedisk='df -hl --total | tail -1'

  # individual partition usages without the temporary memory values
  alias usagepartition='df -hlT --exclude-type=tmpfs --exclude-type=devtmpfs'

  # largest folders within current dir
  function usagehogs {
    du -k * 2>/dev/null | sort -nr | awk '{ if($1>=1024*1024) {size=$1/1024/1024; unit="G"} else if($1>=1024) {size=$1/1024; unit="M"} else {size=$1; unit="K"}; if(size<10) format="%.1f%s"; else format="%.0f%s"; res=sprintf(format,size,unit); printf "%-8s %s\n",res,$2 }'
  }

# unset variables
  unset TTY_COLOR
  unset GNU_TTY_COLOR
  unset GNU_PRESERVE
  unset GNU_i
  unset GNU
